### ISSUE TITLE
要不要前后端分离

### ISSUE THREAD

**Issue by yangyaofei** [wheatup/jandan-comments#3]
就是写两个项目 后端仅仅是根据一个string获取评论,前台写各种插件,或者直接后台带一个命令行的那种.

这样,可以帮写后台,前台实在是不会...

**Comment by wheatup** [comment]
> 就是写两个项目 后端仅仅是根据一个string获取评论,前台写各种插件,或者直接后台带一个命令行的那种.
> 
> 这样,可以帮写后台,前台实在是不会...

可以啊，直接另起一个项目，反正目前我的server文件夹是空的
